
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres   
